### PR TITLE
Feat/Reset password by email

### PR DESCRIPTION
**Pull request by 8bitzz**
### Change-log
- Introduce pages `Forgot password` & `Reset Password` to allow users to reset their password
- Consume APIs `users/request-reset-password` & `users/reset-password`
- Display success/error message according to server's response
- Cleanup useEffect hook for `NavBar` component

### How-to-test
 - Checkout this branch and start frontend, backend server
 - Log out your current account
 - Go to Signup/ Login page then click the `Forgot password` link to navigate to Forgot Password page
 - Use your registered email to check if the users can receive the reset password link in their mailbox (You can use a temporary email from https://temp-mail.org/en/view/6132eb3d46c9f5011919f849 if don't want to use your private email for receiving the reset link)
 - Change the Reset Password URL from `https://cosc-2769-rmit.vercel.app/user/reset-password?` to `localhost:3000/user/reset-password?`
 - Test multiple cases to ensure that 
- [ ] User can not request reset password with an unregistered email
- [ ] User can not use an expired link to reset password (exp. time 15 mins)
- [ ] Users are not able to access page `/user/forgot-password` OR `/user/reset-password` after logging in

Screen Shot 2021-09-04 at 10 42 57

Screen Shot 2021-09-04 at 10 44 02

### CODE REVIEW

**Comment by ManPhamQuang** [comment]
Hi @8bitzz most of the functions tested good. However, I would suggest you add additional logic to protect the route `/user/forgot-password` route so as users who have not logged in can't access the page.
image

**Comment by 8bitzz** [comment]
@ManPhamQuang The current routes `/user/forgot-password` & `/user/reset-password` can be accessed by non-authenticated users only since I only implemented the feature **Forgot Password** & **Reset Password** for users who can't remember password to log into their account (non-authenticated users). Do you mean to implement the **Reset Password** for authenticated users also? In that case, we would create another ticket & implement it in the User Profile Page

**Comment by ManPhamQuang** [comment]
sorry @8bitzz  my mistake, I thought the route `/user/reset-password` should be protected from non-authenticated users, but now that I think about it, it wouldn't make any sense! I'll ask @dangvuthang to review this PR to ensure that it works and then I would approve this branh. Great work 👍

**Comment by dangvuthang** [comment]
The functionality works great as expected. Good job, @8bitzz

**Review by ManPhamQuang — APPROVED** [review]

**Pull request merged**
